[2025-07-09 15:55:23,034 | INFO]: Configuring FichaBot...
[2025-07-09 15:55:23,034 | WARNING]: User plalandelg not found!
[2025-07-09 15:55:23,034 | WARNING]: Creating new user configuration...
[2025-07-09 15:55:23,034 | INFO]: Creating user configuration for plalandelg...
[2025-07-09 15:55:31,797 | ERROR]: [1, 2, 3, 4, 5]
[2025-07-09 15:55:31,802 | ERROR]: Error while running step _config
[2025-07-09 15:55:31,802 | ERROR]: Exception: Invalid weekday format, must be an integer or a range of them, using '-', between 1 and 7
[2025-07-09 15:55:31,833 | ERROR]: Traceback:
Traceback (most recent call last):
  File "D:\plalanda\PLAIN\fichabot\logger.py", line 84, in wrapper
    return runner(*args, **kwargs)
  File "D:\plalanda\PLAIN\fichabot\logger.py", line 51, in wrapper
    result = func(*args, **kwargs)
  File "D:\plalanda\PLAIN\fichabot\config.py", line 144, in _config
    create_user_config(
  File "D:\plalanda\PLAIN\fichabot\config.py", line 97, in create_user_config
    raise ValueError(
ValueError: Invalid weekday format, must be an integer or a range of them, using '-', between 1 and 7

